version: '3.8'

services:
  nginx:
    build: .
    volumes:
      - nginx-data:/usr/share/nginx/html
    networks:
      - vlab-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "8080:80"

networks:
  vlab-network:

volumes:
  nginx-data:
